--Creación de los filegroups: HERRAMIENTAS, CLIENTES, OPERACIONES, MANTENIMIENTO

USE MASTER
GO
ALTER DATABASE ALQUIFACIL
ADD FILEGROUP HERRAMIENTAS
GO

USE MASTER
GO
ALTER DATABASE ALQUIFACIL
ADD FILEGROUP CLIENTES
GO

USE MASTER
GO
ALTER DATABASE ALQUIFACIL
ADD FILEGROUP OPERACIONES
GO

USE MASTER
GO
ALTER DATABASE ALQUIFACIL
ADD FILEGROUP MANTENIMIENTO
GO



USE MASTER
GO 
ALTER DATABASE ALQUIFACIL
ADD FILE
(
    NAME = ALQUIFACIL_Core_Data_01,
    FILENAME = 'C:\SQLData\ALQUIFACIL_Core_Data_01.ndf',
    SIZE = 500MB,
    MAXSIZE = 5GB,
    FILEGROWTH = 10MB
)
TO FILEGROUP HERRAMIENTAS
GO


USE MASTER
GO 
ALTER DATABASE ALQUIFACIL
ADD FILE
(
    NAME = 'ALQUIFACIL_Clientes_Data_01',
    FILENAME = 'C:\SQLData\ALQUIFACIL_Clientes_Data_01.ndf',
    SIZE = 300MB,
    MAXSIZE = 2GB,
    FILEGROWTH = 10MB
)
TO FILEGROUP CLIENTES
GO


USE MASTER
GO 
ALTER DATABASE ALQUIFACIL
ADD FILE
(
    NAME = 'ALQUIFACIL_Operaciones_Data_01',
    FILENAME = 'C:\SQLData\ALQUIFACIL_Operaciones_Data_01.ndf',
    SIZE = 1GB,
    MAXSIZE = 10GB,
    FILEGROWTH = 50MB
),
(
    NAME = 'ALQUIFACIL_Operaciones_Data_02',
    FILENAME = 'C:\SQLData\ALQUIFACIL_Operaciones_Data_02.ndf',
    SIZE = 1GB,
    MAXSIZE = 10GB,
    FILEGROWTH = 50MB
)
TO FILEGROUP OPERACIONES
GO


USE MASTER
GO 
ALTER DATABASE ALQUIFACIL
ADD FILE
(
    NAME = 'ALQUIFACIL_Mantenimiento_Data_01',
    FILENAME = 'C:\SQLData\ALQUIFACIL_Mantenimiento_Data_01.ndf',
    SIZE = 500MB,
    MAXSIZE = 5GB,
    FILEGROWTH = 20MB
)
TO FILEGROUP MANTENIMIENTO
GO